### PR TITLE
Workaround for react-native 0.4.8 contentOffset regression

### LINKED ISSUE #570: react-native 0.48.3 and react-native-swiper - Last slide shown first
### Which OS ?
IOS

### Version
Which versions are you using:

- react-native-swiper v1.5.12 (but it affect every single version of it, tried back to 1.5.4 as well)
- react-native v0.48.3

### Expected behaviour

- The first slide should be first.

### Actual behaviour

- The last slide showed first.
- Awkward pagination display - it shows the state of the first slide, while displaying the last slide.

p.s. If loop={false} is set - everything seems fine.

### How to reproduce it>
Just get the repo from
https://github.com/nixoz/swiperDemo
-

### Steps to reproduce
1. Create mint react-native project
2. Copy paste first example from react-native-swiper README
3. react-native run-ios
4. KABOOM!

### PR DESCRIPTION
**Pull request by nixoz**
### Is it a bugfix ?
- Yes
- fix #570 

### Describe what you've done:
Just added a Swiper flag to track the initial render, and executed scrollView.scrollTo method with the appropriate offset.

### How to test it?
* Use react 0.48.0 with default example from react-native-swiper README.
* it will reproduce the buggy behavior when contentOffset is not applied to ScrollView. (Last page will be displayed first.)
* Apply the current patch. The scrollView.scrollTo should scroll to proper offset on first 'onLayout' call of Swiper.

It is applied only if there are more than 1 slides.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -263,6 +269,17 @@ export default class extends Component {
     if (!this.state.offset || width !== this.state.width || height !== this.state.height) {
       state.offset = offset
     }
+
+    // related to https://github.com/leecade/react-native-swiper/issues/570
+    // contentOffset is not working in react 0.48.x so we need to use scrollTo
+    // to emulate offset.
+    if (Platform.OS === 'ios') {
+      if (this.initialRender && this.props.loop && this.state.total > 1) {
```
Comment (enahum) [inline src/index.js]: Why only if loop is enabled?

Comment (nixoz) [reply src/index.js]: It does not need to make any offset if the loop is not enabled.
In case if the loop is enabled - it unshifting the last page in front of the pages array, and pushing the first page to the back of the array - in this case, we need to maintain offset.

**Comment by enahum** [comment]
This PR is working great at least for me, is there any chance we can review and merge this one?

**Comment by arribbar** [comment]
Thanks  @nixoz and @enahum.

**Comment by stueynet** [comment]
Tag coming for this?

**Comment by arribbar** [comment]
Done

**Comment by ryanvanderpol** [comment]
FYI, this PR *did* fix the initial index issue, but something in this release broke looping for me.  In my app, I render 3 slides and start at index 1.  I can swipe back to index 0 fine, but then to get to index 2 (swiping backwards one more time) I get stuck -- it actually shows the slide at index 2 during the swipe gesture but as soon as it settles in, it's stuck back at index 0.

I ended up backing all the way up to `1.5.10`, which for me, works perfectly.  Every version since then has had some issue.

**Comment by nixoz** [comment]
I agree. 

1. Here is issue in react-native(scroll view contentOffset related one. the patch will be included in 0.50 i guess) 
2. React-native-swiper - was also broken somewhere in previous versions.(i guess after the onLayout handler was introduced, but i might be wrong)

This two factors made the things very confusing.
Have no time right now to dive deeper into the problem but it is absolutely necessary.
